// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reset.sql

package database

import (
	"context"
)

const reset = `-- name: Reset :exec
TRUNCATE users CASCADE
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}
