// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: upgradeUserToRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserToRed = `-- name: UpgradeUserToRed :one
UPDATE users
SET is_chirpy_red = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, email, hashed_password, is_chirpy_red, created_at, updated_at
`

type UpgradeUserToRedParams struct {
	IsChirpyRed bool
	ID          uuid.UUID
}

func (q *Queries) UpgradeUserToRed(ctx context.Context, arg UpgradeUserToRedParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upgradeUserToRed, arg.IsChirpyRed, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
